### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by himanshu64** [alchemyplatform/alchemy-web3#104]
Node => v17.3.0
NPM => 8.3.0

 "react-scripts": "5.0.0",
"@alch/alchemy-web3": "^1.2.4",

sendRestPayload.js:17 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at makeRestPayloadSender (sendRestPayload.js:17:1)
    at makeAlchemyContext (alchemyContext.js:15:1)
    at createAlchemyWeb3 (index.js:20:1)
    at Module../src/services/mint.js (mint.js:7:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/components/mint/index.js (marketing.js:98:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)

**Comment by himanshu64** [comment]
**craco.config.js**

const webpack = require("webpack");
const Dotenv = require('dotenv-webpack');

module.exports = {
  webpack: {
   
    configure: {
      resolve: {
        fallback: {
          "os": require.resolve("os-browserify/browser"),
          zlib: require.resolve("browserify-zlib"),
          stream: require.resolve("stream-browserify"),
          util: require.resolve("util"),
          buffer: require.resolve('buffer/'),
          asset: require.resolve("assert"),
          path: require.resolve("path-browserify"),
          fs: require.resolve("fs"),
          crypto: require.resolve("crypto-browserify"),
          "stream-http": require.resolve("stream-http"),
          http: require.resolve("http-browserify"),
          https: require.resolve("https-browserify"),

        },
      },
      plugins: [
        new webpack.ProvidePlugin({
            Buffer: ['buffer', 'Buffer'],
        }),
        new Dotenv(),
        new webpack.DefinePlugin({
          "process.env": {
            // This has effect on the react lib size
            NODE_ENV: JSON.stringify("development"),
          },
        }),
    ]
    },
  },
};

issue resolved -> dotenv not getting values with webpack5 , so i used this and it's works perfectly file
