### ISSUE TITLE
500 Internal server with npm package on getNFTMetadata, bypassing try/catch statement outside of the npm package

### ISSUE THREAD

**Issue by brucdarc** [alchemyplatform/alchemy-web3#108]
Details: 

Error thrown on line 58 of sendRestPayloaddist/cjs/web3-adapter/sendRestPayload.js seems to bypass outside try catch statements of outside program calling web3.alchemy.getNftMetadata.

Whenever this error occurs and a 500 internal server error comes back from a call, the outside program exists immediately without entering any outside try/catch statements, even if the whole program is wrapped in try catch. Also no luck checking for promise rejections. Could this be because this error is coming from another thread or something?

Full error msg is as follows :
```/home/dak/Desktop/wise/contract_repos/merkle-tree/liquid-pool-merkle-price-tree/generate/node_modules/@alch/alchemy-web3/dist/cjs/web3-adapter/sendRestPayload.js:58
                            throw new Error(response.status + ":" + response.statusText);
                                  ^

Error: 500:Error getting NFT Metadata
    at Object.<anonymous> (/home/dak/Desktop/wise/contract_repos/merkle-tree/liquid-pool-merkle-price-tree/generate/node_modules/@alch/alchemy-web3/dist/cjs/web3-adapter/sendRestPayload.js:58:35)
    at step (/home/dak/Desktop/wise/contract_repos/merkle-tree/liquid-pool-merkle-price-tree/generate/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/dak/Desktop/wise/contract_repos/merkle-tree/liquid-pool-merkle-price-tree/generate/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/dak/Desktop/wise/contract_repos/merkle-tree/liquid-pool-merkle-price-tree/generate/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by thebrianchen** [comment]
@brucdarc Can you provide a repro or a code sample? AFAIK, the library should catch and automatically retry errors.

**Comment by thebrianchen** [comment]
@brucdarc I'm having trouble reproducing this locally, even with your code snippet. If it's not too much work, can you create a repro in a package that I could download and run?
