### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by alexisdavidson** [alchemyplatform/alchemy-web3#117]
Hi, Im using alchemy within a React app but I get the following error:

```
if (!url.includes("alchemy")) {
             ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at Object.makeRestPayloadSender (C:\Users\alexi\Desktop\NFT-Block-Slimes\node_modules\@alch\alchemy-web3\dist\cjs\web3-adapter\sendRestPayload.js:16:14)
    at Object.makeAlchemyContext (C:\Users\alexi\Desktop\NFT-Block-Slimes\node_modules\@alch\alchemy-web3\dist\cjs\web3-adapter\alchemyContext.js:18:40)
    at createAlchemyWeb3 (C:\Users\alexi\Desktop\NFT-Block-Slimes\node_modules\@alch\alchemy-web3\dist\cjs\index.js:21:31)
```

Any help would be appreciated

**Comment by 1dNDN** [comment]
thank u, it helped me
